<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Component\\OptionsResolver\\' => array($vendorDir . '/symfony/options-resolver'),
    'Logentries\\' => array($vendorDir . '/ghostmonitor/logentries'),
    'Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'Billingo\\Plugin\\Helper\\' => array($vendorDir . '/voov/billingo-plugin-helper/src'),
    'Billingo\\API\\Connector\\' => array($vendorDir . '/voov/billingo-api-connector/src'),
);
